@startuml
'https://plantuml.com/class-diagram

class Solution42 {
-Scanner in
+main(String[] args)
-getStringFromUser(String prompt)
+parseJson(String itemToFind, JsonReader jsonReader)
-compareDataToUser(String[] productData, String itemToFind, JsonReader jsonReader)
}


@enduml